llenguatge:
	antlr4 -Dlanguage=Python3 -no-listener -visitor jsbach.g4

executar:
	python3 jsbach.py input.txt

clean:
	rm *.mp3 *.wav *.pdf *.lily *.midi jsbach.interp jsbach.tokens jsbachParser.py jsbachVisitor.py jsbachLexer.py jsbachLexer.tokens jsbachLexer.interp